import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Burgers
  {
    id: 'classic_smash',
    name: 'Classic Smash Burger',
    description: 'Double smashed beef patty, American cheese, pickles, onion, bistro sauce on a brioche bun.',
    price: 13.99,
    category: 'burgers',
    tags: ['bestseller', 'beef'],
    popular: true,
    imageEmoji: '🍔',
  },
  {
    id: 'spicy_crispy_chicken',
    name: 'Spicy Crispy Chicken',
    description: 'Buttermilk fried chicken, ghost pepper aioli, slaw, dill pickles, brioche bun.',
    price: 14.99,
    category: 'burgers',
    tags: ['spicy', 'chicken', 'popular'],
    popular: true,
    imageEmoji: '🌶️',
  },
  {
    id: 'mushroom_swiss',
    name: 'Mushroom Swiss Burger',
    description: 'Beef patty, sautéed mushrooms, Swiss cheese, garlic aioli, arugula.',
    price: 14.49,
    category: 'burgers',
    tags: ['beef', 'mushroom'],
    imageEmoji: '🍄',
  },
  {
    id: 'veggie_smash',
    name: 'Veggie Smash',
    description: 'Black bean & quinoa patty, avocado, pico de gallo, chipotle mayo.',
    price: 12.99,
    category: 'burgers',
    tags: ['vegetarian', 'vegan-option'],
    imageEmoji: '🥑',
  },
  // Sandwiches
  {
    id: 'cuban_pressed',
    name: 'Cuban Pressed',
    description: 'Slow-roasted pork, ham, Swiss cheese, mustard, pickles on pressed Cuban bread.',
    price: 13.49,
    category: 'sandwiches',
    tags: ['pork', 'pressed'],
    popular: true,
    imageEmoji: '🥖',
  },
  {
    id: 'buffalo_chicken_wrap',
    name: 'Buffalo Chicken Wrap',
    description: 'Crispy chicken strips, buffalo sauce, blue cheese crumbles, romaine, tomato.',
    price: 12.49,
    category: 'sandwiches',
    tags: ['spicy', 'chicken'],
    imageEmoji: '🌯',
  },
  {
    id: 'blt_deluxe',
    name: 'BLT Deluxe',
    description: 'Thick-cut bacon, heirloom tomatoes, butter lettuce, avocado, herb mayo on sourdough.',
    price: 11.99,
    category: 'sandwiches',
    tags: ['bacon', 'classic'],
    imageEmoji: '🥪',
  },
  // Sides
  {
    id: 'bistro_fries',
    name: 'Bistro Fries',
    description: 'Hand-cut fries seasoned with rosemary salt, served with bistro dip.',
    price: 4.99,
    category: 'sides',
    tags: ['vegetarian', 'shareable'],
    popular: true,
    imageEmoji: '🍟',
  },
  {
    id: 'onion_rings',
    name: 'Crispy Onion Rings',
    description: 'Beer-battered onion rings with smoky ranch dipping sauce.',
    price: 5.49,
    category: 'sides',
    tags: ['vegetarian'],
    imageEmoji: '🧅',
  },
  {
    id: 'mac_and_cheese',
    name: 'Truffle Mac & Cheese',
    description: 'Three-cheese blend, truffle oil, panko breadcrumb crust.',
    price: 6.99,
    category: 'sides',
    tags: ['vegetarian', 'comfort'],
    imageEmoji: '🧀',
  },
  {
    id: 'side_salad',
    name: 'Garden Side Salad',
    description: 'Mixed greens, cucumber, cherry tomato, red onion, house vinaigrette.',
    price: 4.49,
    category: 'sides',
    tags: ['vegetarian', 'healthy'],
    imageEmoji: '🥗',
  },
  // Drinks
  {
    id: 'craft_lemonade',
    name: 'Craft Lemonade',
    description: 'Freshly squeezed, lightly sweetened, choice of classic or strawberry.',
    price: 3.99,
    category: 'drinks',
    tags: ['non-alcoholic', 'refreshing'],
    popular: true,
    imageEmoji: '🍋',
  },
  {
    id: 'fountain_soda',
    name: 'Fountain Soda',
    description: 'Pepsi, Diet Pepsi, Sierra Mist, Dr Pepper, or Root Beer. Free refills.',
    price: 2.99,
    category: 'drinks',
    tags: ['non-alcoholic'],
    imageEmoji: '🥤',
  },
  {
    id: 'milkshake',
    name: 'House Milkshake',
    description: 'Thick hand-spun shake: vanilla, chocolate, strawberry, or salted caramel.',
    price: 6.49,
    category: 'drinks',
    tags: ['dessert-drink', 'indulgent'],
    popular: true,
    imageEmoji: '🥛',
  },
  {
    id: 'sparkling_water',
    name: 'Sparkling Water',
    description: 'Chilled sparkling mineral water.',
    price: 2.49,
    category: 'drinks',
    tags: ['non-alcoholic', 'healthy'],
    imageEmoji: '💧',
  },
  // Desserts
  {
    id: 'brownie_sundae',
    name: 'Brownie Sundae',
    description: 'Warm fudge brownie, vanilla ice cream, hot fudge, whipped cream, cherry.',
    price: 7.99,
    category: 'desserts',
    tags: ['indulgent', 'shareable'],
    popular: true,
    imageEmoji: '🍨',
  },
  {
    id: 'churro_bites',
    name: 'Churro Bites',
    description: 'Cinnamon-sugar dusted churro bites with dulce de leche dipping sauce.',
    price: 5.99,
    category: 'desserts',
    tags: ['shareable', 'sweet'],
    imageEmoji: '🍩',
  },
];

export const MENU_CATEGORIES = [
  { id: 'burgers', label: 'Burgers', emoji: '🍔' },
  { id: 'sandwiches', label: 'Sandwiches', emoji: '🥖' },
  { id: 'sides', label: 'Sides', emoji: '🍟' },
  { id: 'drinks', label: 'Drinks', emoji: '🥤' },
  { id: 'desserts', label: 'Desserts', emoji: '🍨' },
] as const;
